### ISSUE TITLE
[bug] Sprite attaches padding: 1px to all icons

### ISSUE THREAD

**Issue by mrfr0g** [meltifa/sprity-scss#1]
Expected result:
 Generated sprite doesn't apply layout specific rules to icons. i.e., 'padding: 1px'

Actual result:
 Generated sprite attaches `padding: 1px` to all icons.

This style modifies the positioning of every icon that is generated by sprity, and throws off the alignment of my icons. Please consider removing this rule.

**Comment by meltifa** [comment]
When using REM units, the `background-position` sometimes offset, so I added 1px padding, now it has been separated.
